_wandb:
    value:
        cli_version: 0.28.2
        e:
<<<<<<<< HEAD:wandb/run-20260830_153915-59lzsgud/files/config.yaml
            4oyjoetfkqohqsqt9nh24fkywobalidu:
========
            iiy4cbb7akx65u9jn34bu1gxd6uxcad5:
>>>>>>>> feature/research:wandb/run-20260830_131832-dgx8q7zt/files/config.yaml
                codePath: training_pipeline.py
                codePathLocal: training_pipeline.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "214091239424"
<<<<<<<< HEAD:wandb/run-20260830_153915-59lzsgud/files/config.yaml
                        used: "116948287488"
                email: aliasghare1.ai@gmail.com
                executable: C:\Users\mohammad\PyCharmMiscProject\.venv\Scripts\python.exe
                git:
                    commit: 205376bc0f1f788ca4cbc91d3eb1fc6acdbf9db8
========
                        used: "116468346880"
                email: aliasghare1.ai@gmail.com
                executable: C:\Users\mohammad\PyCharmMiscProject\.venv\Scripts\python.exe
                git:
                    commit: fab707279ca9445d8e21c6621af2cc6dede1e70d
>>>>>>>> feature/research:wandb/run-20260830_131832-dgx8q7zt/files/config.yaml
                    remote: https://github.com/aliasgharebrahimi/MNISTVision.git
                host: Ali-Asghar-Ebrahimi
                memory:
                    total: "16850153472"
                os: Windows-10-10.0.19045-SP0
                program: C:\Users\mohammad\Desktop\Projects\MNISVision\training_pipeline.py
                python: CPython 3.14.2
                root: C:\Users\mohammad\Desktop\Projects\MNISVision
<<<<<<<< HEAD:wandb/run-20260830_153915-59lzsgud/files/config.yaml
                startedAt: "2026-08-30T12:09:15.232173Z"
                writerId: 4oyjoetfkqohqsqt9nh24fkywobalidu
========
                startedAt: "2026-08-30T09:48:32.092390Z"
                writerId: iiy4cbb7akx65u9jn34bu1gxd6uxcad5
>>>>>>>> feature/research:wandb/run-20260830_131832-dgx8q7zt/files/config.yaml
        m: []
        python_version: 3.14.2
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
            "4": 3.14.2
            "5": 0.28.2
            "8":
                - 3
            "12": 0.28.2
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 2
kernel_size:
    value: 3
layers:
    value: 2
learning_rate:
    value: 0.001
optimizer:
    value: Adam
